chore: Update PM2 start command to use yarn serve with bash interpreter

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -6,17 +6,15 @@ name: Node.js CI
 on:
   push:
     branches: [ "pro" ]
-  pull_request:
-    branches: [ "pro" ]
 
 jobs:
   build:
 
-    runs-on: ubuntu-latest
+    runs-on: self-hosted
 
     strategy:
       matrix:
-        node-version: [14.x, 16.x, 18.x]
+        node-version: [20.x]
         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
     steps:
@@ -26,5 +24,28 @@ jobs:
       with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
-    - run: npm ci
-    - run: npm run build --if-present
+    - name: Clean install...
+      run: npm ci
+
+    - name: Run build....
+      run: npm run build --if-present
+
+    - name: Check if PM2 is installed
+      run: |
+        if ! command -v pm2 &> /dev/null
+        then
+            echo "PM2 could not be found, installing..."
+            yarn global add pm2
+        else
+            echo "PM2 is already installed"
+        fi
+
+    - name: Start or Restart PM2 Application
+      run: |
+        pm2 list  # Hiển thị danh sách các ứng dụng hiện đang được quản lý bởi PM2 (để kiểm tra/debug)
+        if pm2 describe cms-smart-shop > /dev/null; then
+          pm2 restart cms-smart-shop
+        else
+          pm2 start yarn --name "cms-smart-shop" -- start
+        fi
+    
